name: Telegram Listener Bot

on:
  schedule:
    # প্রতি ৩ মিনিট পর পর নতুন Telegram কমান্ড আছে কিনা চেক করবে
    - cron: "*/3 * * * *"
  workflow_dispatch: # চাইলে ম্যানুয়ালি চালানো যাবে

permissions:
  contents: write    # ✅ ফাইল লেখার অনুমতি
  actions: write     # ✅ অন্য workflow ট্রিগার করার অনুমতি

jobs:
  run-listener:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ✅ push করতে credential ধরে রাখে

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Telegram Listener Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKE_GITHUB_BOT }}
          GITHUB_OWNER: "fahim12064"
          GITHUB_REPO: "NU-Notice-Bot-Updated-"
        run: python listener.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "🤖 Auto: Listener triggered workflow or updated data" && git push
          )
